### ISSUE TITLE
get https ssl working on api

### ISSUE THREAD

**Issue by bbest** [cstories-app/api#1]
* [cstories.app - Google Domains - DNS](https://domains.google.com/registrar/cstories.app/dns)
  * added `A` type record for `api` subdomain to point to server IP address: http://164.92.110.38/

The SSL certificate could be generated by:
1. Apache, or;
2. Caddy, eg using a docker setup and reverse proxy config like here:
  * [docker-compose.yml · ecoquants/server](https://github.com/ecoquants/server/blob/main/docker-compose.yml)
  * [Caddyfile · ecoquants/server](https://github.com/ecoquants/server/blob/main/caddy/Caddyfile)

**Comment by geocoug** [comment]
Closed via c68ebe6. Using Apache reverse proxy. SSL certs generated using certbot... will need renewal.

**Comment by bbest** [comment]
Bravo @geocoug! I updated the URL in `chat.js` to use httpS://api.cstories.app so now works great!

**Comment by geocoug** [comment]
Good catch, thanks!

One cool feature in our [Apache config](https://github.com/cstories-app/api#reverse-proxy) is it's ability to redirect HTTP requests to HTTPS using the [mod_rewrite](https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html) module directives:

```apache
RewriteEngine on
RewriteCond %{SERVER_NAME} =api.cstories.app
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
```
